#:kivy 1.0

<CountingButton>:
    font_size: 18
    text: 'I have been clicked ' + str(self.count) + ' times.'
    on_press: self.do_action()


<CountingBox>:
    orientation: 'vertical'
    Label:
        font_size: 32
        # Note we want the title of CountingBox, not of Label, so we 
        #   use root.title as opposed to self.title
        text: root.title
    CountingButton:
        count: 0
    CountingButton:
    CountingButton:
        count: 4